// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	"context"
	"time"

	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CiliumStaticIPsGetter has a method to return a CiliumStaticIPInterface.
// A group's client should implement this interface.
type CiliumStaticIPsGetter interface {
	CiliumStaticIPs(namespace string) CiliumStaticIPInterface
}

// CiliumStaticIPInterface has methods to work with CiliumStaticIP resources.
type CiliumStaticIPInterface interface {
	Create(ctx context.Context, ciliumStaticIP *v2alpha1.CiliumStaticIP, opts v1.CreateOptions) (*v2alpha1.CiliumStaticIP, error)
	Update(ctx context.Context, ciliumStaticIP *v2alpha1.CiliumStaticIP, opts v1.UpdateOptions) (*v2alpha1.CiliumStaticIP, error)
	UpdateStatus(ctx context.Context, ciliumStaticIP *v2alpha1.CiliumStaticIP, opts v1.UpdateOptions) (*v2alpha1.CiliumStaticIP, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2alpha1.CiliumStaticIP, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2alpha1.CiliumStaticIPList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumStaticIP, err error)
	CiliumStaticIPExpansion
}

// ciliumStaticIPs implements CiliumStaticIPInterface
type ciliumStaticIPs struct {
	client rest.Interface
	ns     string
}

// newCiliumStaticIPs returns a CiliumStaticIPs
func newCiliumStaticIPs(c *CiliumV2alpha1Client, namespace string) *ciliumStaticIPs {
	return &ciliumStaticIPs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the ciliumStaticIP, and returns the corresponding ciliumStaticIP object, and an error if there is any.
func (c *ciliumStaticIPs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2alpha1.CiliumStaticIP, err error) {
	result = &v2alpha1.CiliumStaticIP{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ciliumstaticips").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CiliumStaticIPs that match those selectors.
func (c *ciliumStaticIPs) List(ctx context.Context, opts v1.ListOptions) (result *v2alpha1.CiliumStaticIPList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2alpha1.CiliumStaticIPList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("ciliumstaticips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested ciliumStaticIPs.
func (c *ciliumStaticIPs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("ciliumstaticips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a ciliumStaticIP and creates it.  Returns the server's representation of the ciliumStaticIP, and an error, if there is any.
func (c *ciliumStaticIPs) Create(ctx context.Context, ciliumStaticIP *v2alpha1.CiliumStaticIP, opts v1.CreateOptions) (result *v2alpha1.CiliumStaticIP, err error) {
	result = &v2alpha1.CiliumStaticIP{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("ciliumstaticips").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ciliumStaticIP).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a ciliumStaticIP and updates it. Returns the server's representation of the ciliumStaticIP, and an error, if there is any.
func (c *ciliumStaticIPs) Update(ctx context.Context, ciliumStaticIP *v2alpha1.CiliumStaticIP, opts v1.UpdateOptions) (result *v2alpha1.CiliumStaticIP, err error) {
	result = &v2alpha1.CiliumStaticIP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ciliumstaticips").
		Name(ciliumStaticIP.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ciliumStaticIP).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *ciliumStaticIPs) UpdateStatus(ctx context.Context, ciliumStaticIP *v2alpha1.CiliumStaticIP, opts v1.UpdateOptions) (result *v2alpha1.CiliumStaticIP, err error) {
	result = &v2alpha1.CiliumStaticIP{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("ciliumstaticips").
		Name(ciliumStaticIP.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(ciliumStaticIP).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the ciliumStaticIP and deletes it. Returns an error if one occurs.
func (c *ciliumStaticIPs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ciliumstaticips").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *ciliumStaticIPs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("ciliumstaticips").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched ciliumStaticIP.
func (c *ciliumStaticIPs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2alpha1.CiliumStaticIP, err error) {
	result = &v2alpha1.CiliumStaticIP{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("ciliumstaticips").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
