// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CiliumStaticIPLister helps list CiliumStaticIPs.
// All objects returned here must be treated as read-only.
type CiliumStaticIPLister interface {
	// List lists all CiliumStaticIPs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.CiliumStaticIP, err error)
	// CiliumStaticIPs returns an object that can list and get CiliumStaticIPs.
	CiliumStaticIPs(namespace string) CiliumStaticIPNamespaceLister
	CiliumStaticIPListerExpansion
}

// ciliumStaticIPLister implements the CiliumStaticIPLister interface.
type ciliumStaticIPLister struct {
	indexer cache.Indexer
}

// NewCiliumStaticIPLister returns a new CiliumStaticIPLister.
func NewCiliumStaticIPLister(indexer cache.Indexer) CiliumStaticIPLister {
	return &ciliumStaticIPLister{indexer: indexer}
}

// List lists all CiliumStaticIPs in the indexer.
func (s *ciliumStaticIPLister) List(selector labels.Selector) (ret []*v2alpha1.CiliumStaticIP, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.CiliumStaticIP))
	})
	return ret, err
}

// CiliumStaticIPs returns an object that can list and get CiliumStaticIPs.
func (s *ciliumStaticIPLister) CiliumStaticIPs(namespace string) CiliumStaticIPNamespaceLister {
	return ciliumStaticIPNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// CiliumStaticIPNamespaceLister helps list and get CiliumStaticIPs.
// All objects returned here must be treated as read-only.
type CiliumStaticIPNamespaceLister interface {
	// List lists all CiliumStaticIPs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v2alpha1.CiliumStaticIP, err error)
	// Get retrieves the CiliumStaticIP from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v2alpha1.CiliumStaticIP, error)
	CiliumStaticIPNamespaceListerExpansion
}

// ciliumStaticIPNamespaceLister implements the CiliumStaticIPNamespaceLister
// interface.
type ciliumStaticIPNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CiliumStaticIPs in the indexer for a given namespace.
func (s ciliumStaticIPNamespaceLister) List(selector labels.Selector) (ret []*v2alpha1.CiliumStaticIP, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v2alpha1.CiliumStaticIP))
	})
	return ret, err
}

// Get retrieves the CiliumStaticIP from the indexer for a given namespace and name.
func (s ciliumStaticIPNamespaceLister) Get(name string) (*v2alpha1.CiliumStaticIP, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v2alpha1.Resource("ciliumstaticip"), name)
	}
	return obj.(*v2alpha1.CiliumStaticIP), nil
}
